apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  namespace: nginx
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:ap-northeast-2:381492076830:certificate/53951246-9dba-46c1-a4ef-2b488eb042e7
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
    alb.ingress.kubernetes.io/ssl-policy: ELBSecurityPolicy-2016-08
spec:
  ingressClassName: alb
  rules:
  - host: kiminji.store
    http: 
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: index-service
            port:
              number: 80
      - path: /login.jsp
        pathType: Prefix
        backend:
          service:
            name: login-service
            port:
              number: 80
      - path: /join.jsp
        pathType: Prefix
        backend:
          service:
            name: join-service
            port:
              number: 80
      - path: /contents.jsp
        pathType: Prefix
        backend:
          service:
            name: contents-service
            port:
              number: 80
      - path: /mypage.jsp
        pathType: Prefix
        backend:
          service:
            name: mypage-service
            port:
              number: 80
  - host: '*.kiminji.store'
    http: 
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: index-service
            port:
              number: 80
      - path: /login.jsp
        pathType: Prefix
        backend:
          service:
            name: login-service
            port:
              number: 80
      - path: /join.jsp
        pathType: Prefix
        backend:
          service:
            name: join-service
            port:
              number: 80
      - path: /contents.jsp
        pathType: Prefix
        backend:
          service:
            name: contents-service
            port:
              number: 80
      - path: /mypage.jsp
        pathType: Prefix
        backend:
          service:
            name: mypage-service
            port:
              number: 80            
